language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 12
  - 14
install: npm install
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta
    - next

jobs:
  include:
    - stage: release
      node_js: 14
      env:
        - DEBUG=semantic-release:*
      script: kcd-scripts travis-release
      if: fork = false
